---
logging: info
certificate: etc/server.crt
private_key: etc/server.key

# host:port
listen:
- *:4010

users:
- example_user:
    password: password

    networks:
    - malkier:
        servers: irc.malkier.net:6667
        channels:
        - "#malkier"
        - "#lobby"

    - freenode:
        servers: chat.freenode.net:6667
        channels:
        - "#freenode"
